# Generated by Django 5.1.15 on 2026-08-21 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorefrontBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement bar'), ('HOME_HERO', 'Homepage hero')], max_length=16)),
                ('message', models.CharField(blank=True, help_text='Announcement bar copy (one line).', max_length=200)),
                ('title', models.CharField(blank=True, help_text='Hero headline.', max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(blank=True, max_length=40)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('dismissible', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Highest priority wins when several are live.')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_storefrontbanner',
                'ordering': ('-priority', '-created_at'),
                'indexes': [models.Index(fields=['placement', '-priority'], name='content_banner_place_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='content_banner_window_ordered')],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.CharField(choices=[('HEADER', 'Header'), ('FOOTER', 'Footer')], default='HEADER', max_length=16)),
                ('type', models.CharField(choices=[('CATEGORY', 'Category'), ('LINK', 'Link'), ('PROMO', 'Promo card')], default='CATEGORY', max_length=16)),
                ('label', models.CharField(blank=True, help_text='Overrides the category name when set.', max_length=120)),
                ('url', models.CharField(blank=True, help_text='LINK and PROMO items only, e.g. /shop?sort=newest', max_length=300)),
                ('badge', models.CharField(blank=True, help_text='Rendered as data, e.g. "NEW", "SALE", "20% OFF". Never branched on.', max_length=24)),
                ('image', models.ImageField(blank=True, null=True, upload_to='navigation/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('layout', models.CharField(choices=[('AUTO', 'Automatic'), ('DROPDOWN', 'Dropdown'), ('MEGA', 'Mega menu')], default='AUTO', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='CATEGORY items only. Supplies the name, slug and children.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='catalog.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navigationitem')),
            ],
            options={
                'db_table': 'content_navigationitem',
                'ordering': ('position', 'label'),
                'indexes': [models.Index(fields=['placement', 'position'], name='content_navitem_place_idx'), models.Index(fields=['parent', 'position'], name='content_navitem_parent_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='content_navitem_window_ordered')],
            },
        ),
    ]
