# Generated by Django 5.1.15 on 2026-09-26 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube'), ('WHATSAPP', 'WhatsApp'), ('MESSENGER', 'Messenger'), ('X', 'X (Twitter)'), ('LINKEDIN', 'LinkedIn'), ('PINTEREST', 'Pinterest'), ('THREADS', 'Threads'), ('TELEGRAM', 'Telegram')], max_length=16, unique=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_visible', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'content_sociallink',
                'ordering': ('position', 'platform'),
            },
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='type',
            field=models.CharField(choices=[('CATEGORY', 'Category'), ('LINK', 'Link'), ('PROMO', 'Promo card'), ('PAGE', 'Site page'), ('GROUP', 'Footer column'), ('CATEGORY_LIST', 'Top categories (automatic)')], default='CATEGORY', max_length=16),
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_sitepage',
                'ordering': ('-is_system', 'title'),
            },
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='PAGE items only. The link follows the page and hides when it is unpublished.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='content.sitepage'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='default', editable=False, max_length=16, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True, help_text="Shown under the footer logo. Blank uses the organisation's.")),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.JSONField(blank=True, default=list, help_text='Rows of {"days": "Saturday–Thursday", "hours": "10:00–20:00"}.')),
                ('show_address', models.BooleanField(default=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL. Only https://www.google.com/maps is accepted.', max_length=2000)),
                ('map_link_url', models.URLField(blank=True, help_text='The "Open in Google Maps" link.', max_length=500)),
                ('copyright_text', models.CharField(blank=True, help_text='{year} is replaced with the current year.', max_length=200)),
                ('bottom_note', models.CharField(blank=True, max_length=200)),
                ('whatsapp_float', models.BooleanField(default=True, help_text='Show the floating chat button when a WhatsApp link is visible.')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'db_table': 'content_sitesettings',
            },
        ),
    ]
