# Generated by Django 5.1.5 on 2026-08-17 17:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'orders_cartitem',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HeldSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('register', models.CharField(blank=True, max_length=32)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict, help_text='Cart lines, discounts and notes.')),
            ],
            options={
                'db_table': 'orders_heldsale',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('channel', models.CharField(choices=[('POS', 'Point of sale'), ('ONLINE', 'Online store'), ('PHONE', 'Phone order'), ('SOCIAL', 'Social media'), ('OTHER', 'Other')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return requested'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=24)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('PARTIALLY_REFUNDED', 'Partially refunded'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=24)),
                ('register', models.CharField(blank=True, max_length=32)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('manual_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('refunded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('customer_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('guest_token', models.CharField(blank=True, help_text='Lets a guest track their order without an account.', max_length=64)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('stock_committed', models.BooleanField(default=False, help_text='True once reservations have become SALE ledger rows.')),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ('-placed_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'Order created'), ('STATUS_CHANGED', 'Status changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_CAPTURED', 'Payment captured'), ('PAYMENT_FAILED', 'Payment failed'), ('REFUND_ISSUED', 'Refund issued'), ('SHIPMENT_CREATED', 'Shipment created'), ('SHIPMENT_EVENT', 'Shipment update'), ('RETURN_REQUESTED', 'Return requested'), ('RETURN_UPDATED', 'Return updated'), ('NOTE_ADDED', 'Note added'), ('CANCELLED', 'Cancelled'), ('STOCK_RESERVED', 'Stock reserved'), ('STOCK_COMMITTED', 'Stock deducted'), ('STOCK_RELEASED', 'Stock released')], max_length=32)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_customer_visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'orders_orderevent',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=200)),
                ('variant_label', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weighted average cost frozen at sale time (ADR-0006).', max_digits=14)),
                ('line_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('fulfilled_quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'orders_orderitem',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MFS', 'Mobile financial service'), ('BANK', 'Bank transfer'), ('ONLINE_GATEWAY', 'Online gateway'), ('COD', 'Cash on delivery'), ('STORE_CREDIT', 'Store credit'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('VOIDED', 'Voided'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='PENDING', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tendered_amount', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Cash handed over, for change calculation.', max_digits=14, null=True)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('provider', models.CharField(default='manual', max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('reference', models.CharField(blank=True, help_text='Slip number, MFS transaction id, cheque number.', max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'db_table': 'orders_payment',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'orders_paymentevent',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MFS', 'Mobile financial service'), ('BANK', 'Bank transfer'), ('ONLINE_GATEWAY', 'Online gateway'), ('COD', 'Cash on delivery'), ('STORE_CREDIT', 'Store credit'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
            ],
            options={
                'db_table': 'orders_refund',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('restock_decision', models.CharField(choices=[('RESTOCK', 'Back to sellable stock'), ('DAMAGED', 'Written off as damaged'), ('QUARANTINE', 'Quarantined for inspection')], default='RESTOCK', max_length=16)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
            options={
                'db_table': 'orders_returnitem',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Goods received'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=16)),
                ('reason', models.CharField(choices=[('WRONG_SIZE', 'Wrong size'), ('DEFECTIVE', 'Defective'), ('WRONG_PRODUCT', 'Wrong product delivered'), ('CUSTOMER_CHANGED_MIND', 'Changed mind'), ('DAMAGED', 'Damaged in transit'), ('OTHER', 'Other')], max_length=32)),
                ('customer_comment', models.TextField(blank=True)),
                ('staff_comment', models.TextField(blank=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('refund_shipping', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_returnrequest',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(help_text='Guest cart identifier (X-Cart-Token).', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='accounts.branch')),
            ],
            options={
                'db_table': 'orders_cart',
                'ordering': ('-last_activity_at',),
            },
        ),
    ]
