# Generated by Django 5.1.15 on 2026-08-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Where this money landed. Set when the payment is captured.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='refund',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Where this money came out of.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.account'),
        ),
    ]
