# Generated by Django 5.1.15 on 2026-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_payment_account_refund_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("EXCLUSIVE", "Added on top of the shown price"),
                    ("INCLUSIVE", "Already included in the shown price"),
                ],
                default="EXCLUSIVE",
                help_text="Whether tax_total sits inside subtotal or was added on top.",
                max_length=16,
            ),
        ),
    ]
