# Generated by Django 5.1.15 on 2026-09-12 19:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_vat_settings'),
        ('customers', '0004_canonical_phone_numbers'),
        ('orders', '0004_order_tax_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RECOVERED', 'Recovered'), ('LOST', 'Lost')], db_index=True, default='OPEN', max_length=16)),
                ('cart_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abandoned_checkouts', to='accounts.branch')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.cart')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customer')),
                ('recovered_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.order')),
            ],
            options={
                'db_table': 'orders_abandonedcheckout',
                'ordering': ('-last_seen_at',),
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='orders_aband_status_seen_idx'), models.Index(fields=['branch', 'status'], name='orders_aband_branch_stat_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('phone',), name='orders_abandonedcheckout_one_open_per_phone')],
            },
        ),
    ]
