# Generated by Django 5.1.15 on 2026-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_abandonedcheckout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Order created'), ('STATUS_CHANGED', 'Status changed'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_CAPTURED', 'Payment captured'), ('PAYMENT_FAILED', 'Payment failed'), ('REFUND_ISSUED', 'Refund issued'), ('SHIPMENT_CREATED', 'Shipment created'), ('SHIPMENT_EVENT', 'Shipment update'), ('RETURN_REQUESTED', 'Return requested'), ('RETURN_UPDATED', 'Return updated'), ('NOTE_ADDED', 'Note added'), ('CANCELLED', 'Cancelled'), ('STOCK_RESERVED', 'Stock reserved'), ('STOCK_COMMITTED', 'Stock deducted'), ('STOCK_RELEASED', 'Stock released'), ('STOCK_SHORT', 'Stock short')], max_length=32),
        ),
    ]
