# Generated by Django 5.1.5 on 2026-08-17 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_code', models.CharField(blank=True, help_text='Everyone holding this code sees the notification.', max_length=64)),
                ('notification_type', models.CharField(choices=[('NEW_ONLINE_ORDER', 'New online order'), ('PAYMENT_RECEIVED', 'Payment received'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('ORDER_SHIPPED', 'Order shipped'), ('ORDER_DELIVERED', 'Order delivered'), ('RETURN_REQUESTED', 'Return requested'), ('REFUND_COMPLETED', 'Refund completed'), ('STOCK_EXPIRING', 'Stock expiring'), ('INTEGRITY_ALERT', 'Inventory integrity alert')], max_length=32)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.branch')),
                ('user', models.ForeignKey(blank=True, help_text='Null means it is addressed to a permission group rather than a person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_554261_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx')],
            },
        ),
    ]
