# Generated by Django 5.1.15 on 2026-09-10 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_ONLINE_ORDER", "New online order"),
                    ("PAYMENT_RECEIVED", "Payment received"),
                    ("LOW_STOCK", "Low stock"),
                    ("OUT_OF_STOCK", "Out of stock"),
                    ("ORDER_CONFIRMED", "Order confirmed"),
                    ("ORDER_SHIPPED", "Order shipped"),
                    ("ORDER_DELIVERED", "Order delivered"),
                    ("RETURN_REQUESTED", "Return requested"),
                    ("REFUND_COMPLETED", "Refund completed"),
                    ("STOCK_EXPIRING", "Stock expiring"),
                    ("INTEGRITY_ALERT", "Inventory integrity alert"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SmsMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "to",
                    models.CharField(
                        db_index=True,
                        help_text="Canonical 8801XXXXXXXXX. What the provider was given, not what it sent.",
                        max_length=32,
                    ),
                ),
                ("body", models.TextField()),
                ("provider", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("SUPPRESSED", "Suppressed"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="The provider's own id for the message.",
                        max_length=128,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "segments",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Billable parts. Bengali is UCS-2, so 70 characters, not 160.",
                    ),
                ),
                ("notification_type", models.CharField(blank=True, max_length=32)),
                (
                    "order_number",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notifications_smsmessage",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="notificatio_status_bcb577_idx",
                    ),
                    models.Index(
                        fields=["order_number", "-created_at"],
                        name="notificatio_order_n_dddbe7_idx",
                    ),
                ],
            },
        ),
    ]
