# Generated by Django 5.1.15 on 2026-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_smsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_ONLINE_ORDER', 'New online order'), ('PAYMENT_RECEIVED', 'Payment received'), ('LOW_STOCK', 'Low stock'), ('OUT_OF_STOCK', 'Out of stock'), ('ORDER_CONFIRMED', 'Order confirmed'), ('ORDER_SHIPPED', 'Order shipped'), ('ORDER_DELIVERED', 'Order delivered'), ('RETURN_REQUESTED', 'Return requested'), ('REFUND_COMPLETED', 'Refund completed'), ('STOCK_EXPIRING', 'Stock expiring'), ('INTEGRITY_ALERT', 'Inventory integrity alert'), ('ORDER_STOCK_SHORT', 'Online order short of stock')], max_length=32),
        ),
    ]
