# Generated by Django 5.1.15 on 2026-08-21 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productimage_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=120, unique=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('last_result_count', models.IntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalog_searchterm',
                'ordering': ('-hits', 'term'),
                'indexes': [models.Index(fields=['-hits'], name='catalog_searchterm_hits_idx'), models.Index(fields=['last_result_count'], name='catalog_searchterm_res_idx')],
            },
        ),
    ]
