# Generated by Django 5.1.15 on 2026-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_searchterm"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tax_rate__isnull", True),
                    models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 1)),
                    _connector="OR",
                ),
                name="catalog_category_tax_rate_range",
            ),
        ),
    ]
