# Generated by Django 5.1.15 on 2026-09-14 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_category_catalog_category_tax_rate_range"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_links",
                        to="catalog.attributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spec_values",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_productattributevalue",
                "ordering": (
                    "attribute_value__attribute__position",
                    "attribute_value__attribute__name",
                    "attribute_value__position",
                    "attribute_value__value",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "attribute_value"),
                        name="catalog_productattr_uniq",
                    )
                ],
            },
        ),
    ]
