# Generated by Django 5.1.15 on 2026-09-27 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productattributevalue"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeChart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        help_text="Sizing system, e.g. International, UK, EU, US.",
                        max_length=40,
                    ),
                ),
                ("columns", models.JSONField(blank=True, default=list)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="How to measure, shown under the chart."
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="size_charts",
                        to="catalog.attribute",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "catalog_sizechart",
                "ordering": ("position", "name"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="size_chart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.sizechart",
            ),
        ),
        migrations.CreateModel(
            name="SizeChartRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cells", models.JSONField(blank=True, default=list)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="size_chart_rows",
                        to="catalog.attributevalue",
                    ),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="catalog.sizechart",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_sizechartrow",
                "ordering": ("attribute_value__position", "attribute_value__value"),
            },
        ),
        migrations.AddConstraint(
            model_name="sizechart",
            constraint=models.UniqueConstraint(
                fields=("attribute", "name"), name="catalog_sizechart_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="sizechartrow",
            constraint=models.UniqueConstraint(
                fields=("chart", "attribute_value"), name="catalog_sizechartrow_uniq"
            ),
        ),
    ]
