// Copy drizzle-kit's introspection of the Django-migrated database into
// src/database/, minus the foreign-key constraint blocks.
//
// Those blocks exist for Drizzle's own migrations, which this project never
// runs -- Django owns the schema. They also make the tables reference each
// other in cycles (branch -> organization -> user -> branch) that TypeScript
// cannot type, and relations.ts already carries every join the ORM needs.
import { readFileSync, writeFileSync } from 'node:fs';

const header = `// GENERATED by \`npm run db:pull\` from a database Django has migrated.
// Do not edit: change the Django model, migrate, and pull again.
`;

const schema = readFileSync('drizzle-pull/schema.ts', 'utf8')
  .replace(/\n\tforeignKey\(\{[\s\S]*?\n\t\t\}\),/g, '')
  .replace(/\bforeignKey, /, '');
if (/foreignKey\(/.test(schema)) throw new Error('A foreignKey block survived; the generator format changed.');
writeFileSync('src/database/schema.ts', header + schema);
writeFileSync('src/database/relations.ts', header + readFileSync('drizzle-pull/relations.ts', 'utf8'));
console.log('src/database/schema.ts and relations.ts updated.');
