# Generated by Django 5.1.5 on 2026-08-17 17:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COUNTING', 'Counting'), ('APPLIED', 'Applied'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_stockcount',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounts.branch')),
                ('target_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounts.branch')),
            ],
            options={
                'db_table': 'inventory_stocktransfer',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_stocktransferitem',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Weighted average cost at this branch (ADR-0006).', max_digits=14)),
                ('reorder_point', models.IntegerField(default=5)),
                ('bin_location', models.CharField(blank=True, max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='accounts.branch')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='catalog.productvariant')),
            ],
            options={
                'verbose_name_plural': 'inventory',
                'db_table': 'inventory_inventory',
                'indexes': [models.Index(fields=['branch', 'variant'], name='inventory_i_branch__ead758_idx'), models.Index(fields=['variant'], name='inventory_i_variant_3983b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'variant'), name='inventory_branch_variant_uniq'), models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='inventory_on_hand_gte_0'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='inventory_reserved_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase received'), ('SALE', 'Sale'), ('RETURN', 'Customer return'), ('DAMAGE', 'Damaged'), ('LOSS', 'Lost or stolen'), ('ADJUSTMENT', 'Manual adjustment'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('RESERVATION', 'Reserved for an order'), ('RESERVATION_RELEASE', 'Reservation released'), ('PURCHASE_RETURN', 'Returned to supplier')], max_length=24)),
                ('quantity', models.IntegerField(help_text='Signed delta applied by this row.')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True)),
                ('on_hand_after', models.IntegerField()),
                ('reserved_after', models.IntegerField()),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_inventorytransaction',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['branch', 'variant', '-created_at'], name='inventory_i_branch__331bac_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_i_referen_ace22e_idx'), models.Index(fields=['transaction_type', '-created_at'], name='inventory_i_transac_307b2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.IntegerField(default=0)),
                ('counted_quantity', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_stockcountitem',
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'variant'), name='inventory_countitem_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_branch', models.F('target_branch')), _negated=True), name='inventory_transfer_distinct_branches'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'variant'), name='inventory_transferitem_uniq'),
        ),
    ]
