# Generated by Django 5.1.5 on 2026-08-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='inventory_on_hand_gte_0',
        ),
    ]
