# Generated by Django 5.1.15 on 2026-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_inventory_inventory_on_hand_gte_0"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
