# Generated by Django 5.1.15 on 2026-09-01 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_vat_settings"),
        ("catalog", "0005_category_catalog_category_tax_rate_range"),
        ("inventory", "0002_remove_inventory_inventory_on_hand_gte_0"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shortfall", models.PositiveIntegerField()),
                (
                    "on_hand_after",
                    models.IntegerField(
                        help_text="Balance immediately after the movement. Negative, by definition."
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESTOCKED", "Stock arrived and covers it"),
                            ("WRITTEN_OFF", "Written off as lost"),
                            ("COUNTED", "Corrected by a stock count"),
                            ("NOT_AN_ERROR", "Expected — no action needed"),
                        ],
                        max_length=16,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_exceptions",
                        to="accounts.branch",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_exception",
                        to="inventory.inventorytransaction",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_exceptions",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_stockexception",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="inventory_s_status_58a958_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("shortfall__gt", 0)),
                        name="inventory_stockexception_shortfall_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("resolution", ""),
                                ("resolved_at__isnull", True),
                                ("status", "OPEN"),
                            ),
                            models.Q(
                                ("resolved_at__isnull", False),
                                ("status", "RESOLVED"),
                                models.Q(("resolution", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="inventory_stockexception_resolution_consistent",
                    ),
                ],
            },
        ),
    ]
