# Generated by Django 5.1.15 on 2026-10-03 15:39
"""Barcode label marks: which variants a branch has finished labelling.

Safe to run against a live database. This migration only **creates** one new,
empty table (`inventory_labelprint`) and its index. It alters, renames, drops
and rewrites nothing that already exists -- no column on any existing table is
touched, so no product, stock row, order or ledger entry can change. The new
foreign keys point *from* the new table, so adding them cannot fail on old data.
`tests/test_label_print_migration.py` holds every later migration to the same
standard for this table.

Rolling it back drops only this table, and so only the marks recorded in it.
"""

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_counter_sells_reserved'),
        ('catalog', '0007_size_charts'),
        ('inventory', '0003_inventorytransaction_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed', models.BooleanField(default=True, help_text='False is an un-mark: the newest row is the state.')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Labels the person reported printing in this run.')),
                ('on_hand', models.IntegerField(default=0, help_text='Stock at the branch when this was marked.')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_prints', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='label_prints', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_labelprint',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['branch', 'variant', '-created_at'], name='inventory_l_branch__94782b_idx')],
            },
        ),
    ]
