# Generated by Django 5.1.15 on 2026-09-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_completed_transfers(apps, schema_editor):
    """Historical transfers were one-step: dispatch and receipt happened together.

    Their rows are `RECEIVED` with no `received_quantity`, which the new
    properties would read as "nothing arrived, everything was lost". The goods
    did arrive -- the old `transfer()` wrote both ledger movements in one
    transaction -- so record that rather than leaving the history lying.

    `dispatched_at` and `received_at` both become `created_at` because that is
    the truth about those transfers: there was no gap between the two.
    """
    StockTransfer = apps.get_model("inventory", "StockTransfer")
    StockTransferItem = apps.get_model("inventory", "StockTransferItem")

    completed = StockTransfer.objects.filter(status="RECEIVED")
    for transfer in completed.iterator():
        StockTransferItem.objects.filter(transfer=transfer, received_quantity__isnull=True).update(
            received_quantity=models.F("quantity")
        )
    completed.filter(dispatched_at__isnull=True).update(dispatched_at=models.F("created_at"))
    completed.filter(received_at__isnull=True).update(received_at=models.F("created_at"))


def unbackfill(apps, schema_editor):
    """Reversible: drop the inferred figures, keep the rows."""
    StockTransferItem = apps.get_model("inventory", "StockTransferItem")
    StockTransferItem.objects.update(received_quantity=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_vat_settings"),
        ("catalog", "0005_category_catalog_category_tax_rate_range"),
        ("inventory", "0003_stockexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransferitem",
            name="received_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "CANCELLED"), _negated=True),
                    models.Q(("cancellation_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="inventory_transfer_cancellation_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransferitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("received_quantity__isnull", True),
                    ("received_quantity__lte", models.F("quantity")),
                    _connector="OR",
                ),
                name="inventory_transferitem_received_lte_sent",
            ),
        ),
        migrations.RunPython(backfill_completed_transfers, unbackfill),
    ]
