# Generated by Django 5.1.15 on 2026-08-31 16:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="default_tax_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Fraction, not a percentage: 0.0750 is 7.5%. Categories may override it.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_mode",
            field=models.CharField(
                choices=[
                    ("EXCLUSIVE", "Added on top of the shown price"),
                    ("INCLUSIVE", "Already included in the shown price"),
                ],
                default="EXCLUSIVE",
                help_text="Whether catalogue prices already contain VAT.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_settled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the owner last confirmed the VAT treatment. Null means never decided.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_settled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tax_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("default_tax_rate__gte", 0), ("default_tax_rate__lte", 1)
                ),
                name="accounts_organization_default_tax_rate_range",
            ),
        ),
    ]
