# Generated by Django 5.1.15 on 2026-09-25 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_vat_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(blank=True, help_text='Job title, e.g. Senior cashier', max_length=80)),
                ('joined_on', models.DateField(blank=True, help_text='First day of employment', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, help_text='NID, birth registration or passport number', max_length=32)),
                ('blood_group', models.CharField(blank=True, choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], max_length=8)),
                ('present_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=60)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_staffprofile',
                'constraints': [models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('national_id',), name='accounts_staffprofile_national_id_uniq')],
            },
        ),
    ]
