# Generated by Django 5.1.15 on 2026-10-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='counter_sells_reserved',
            field=models.BooleanField(default=False, help_text='Let a counter sale take units reserved for online orders.'),
        ),
    ]
