# Generated by Django 5.1.15 on 2026-08-21 20:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('CASH', 'Cash drawer'), ('BANK', 'Bank account'), ('MFS', 'Mobile financial service'), ('OTHER', 'Other')], default='CASH', max_length=16)),
                ('account_number', models.CharField(blank=True, help_text='Bank account or MFS wallet number, if any.', max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transactional cache over AccountTransaction. Written only by finance.services.', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text="Where this branch's money of this kind lands by default.")),
                ('allow_overdraft', models.BooleanField(default=False, help_text='A cash drawer cannot go negative; a bank account with an overdraft line can.')),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_account',
                'ordering': ('branch__name', 'kind', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening balance'), ('SALE_PAYMENT', 'Payment received from a customer'), ('REFUND', 'Refund paid to a customer'), ('SUPPLIER_PAYMENT', 'Payment made to a supplier'), ('EXPENSE', 'Expense paid'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out'), ('DEPOSIT', 'Manual deposit'), ('WITHDRAWAL', 'Manual withdrawal'), ('ADJUSTMENT', 'Correction')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Signed delta applied by this row.', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reference_type', models.CharField(blank=True, db_index=True, max_length=32)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When the money actually moved, which may predate the entry.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_accounttransaction',
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account')),
            ],
            options={
                'db_table': 'finance_accounttransfer',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['branch', 'kind'], name='finance_acc_branch__bdfc28_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active', 'branch'], name='finance_acc_is_acti_fe6970_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='finance_account_branch_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('branch', 'kind'), name='finance_account_branch_kind_default_uniq'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account', '-occurred_at'], name='finance_acc_account_09bfc3_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='finance_acc_referen_aff590_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['transaction_type', '-occurred_at'], name='finance_acc_transac_6b7043_idx'),
        ),
        migrations.AddConstraint(
            model_name='accounttransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_accounttransfer_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='accounttransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_account', models.F('target_account')), _negated=True), name='finance_accounttransfer_distinct_accounts'),
        ),
    ]
