# Generated by Django 5.1.15 on 2026-08-27 04:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("finance", "0002_default_cash_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short stable key, e.g. RENT. Never reused.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "expense categories",
                "db_table": "finance_expensecategory",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "spent_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the money was spent, which may predate the entry.",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="A receipt or a bill, if there is one.",
                        upload_to="expenses/%Y/%m/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("RECORDED", "Recorded"), ("VOID", "Voided")],
                        default="RECORDED",
                        max_length=16,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.account",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="accounts.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal",
                    models.OneToOneField(
                        blank=True,
                        help_text="The compensating row written when this expense was voided.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_expense",
                        to="finance.accounttransaction",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        help_text="The cash-book row this expense posted.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense",
                        to="finance.accounttransaction",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.expensecategory",
                    ),
                ),
            ],
            options={
                "db_table": "finance_expense",
                "ordering": ("-spent_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["branch", "-spent_at"],
                        name="finance_exp_branch__43ad6e_idx",
                    ),
                    models.Index(
                        fields=["category", "-spent_at"],
                        name="finance_exp_categor_550abd_idx",
                    ),
                    models.Index(
                        fields=["status", "-spent_at"],
                        name="finance_exp_status_259f01_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="finance_expense_amount_gt_0",
                    )
                ],
            },
        ),
    ]
