# Generated by Django 5.1.15 on 2026-09-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_default_expense_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="accounttransfer",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
