# Generated by Django 5.1.15 on 2026-09-23 06:55
#
# No SQL: `upload_to` lives in Python. A receipt uploaded from here on is stored
# under a random name rather than the uploader's own (D91). Files already on
# disk keep their names -- they are no longer served from /media/ at all, so a
# guessable name there reaches nothing.

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_accounttransaction_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="A receipt or a bill, if there is one.",
                upload_to=finance.models.expense_attachment_path,
            ),
        ),
    ]
