# Generated by Django 5.1.5 on 2026-08-17 17:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('tracking_url_template', models.CharField(blank=True, help_text='e.g. https://courier.example/track/{tracking_number}', max_length=255)),
                ('integration', models.CharField(default='manual', help_text="Provider code; 'manual' means no API.", max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_courier',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=48)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('free_over', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Free shipping above this order subtotal.', max_digits=14, null=True)),
                ('min_days', models.PositiveSmallIntegerField(default=1)),
                ('max_days', models.PositiveSmallIntegerField(default=3)),
                ('is_pickup', models.BooleanField(default=False)),
                ('supports_cod', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'shipping_shippingmethod',
                'ordering': ('position', 'price'),
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('cities', models.JSONField(blank=True, default=list, help_text='Lower-cased city/district names in this zone.')),
                ('is_default', models.BooleanField(default=False, help_text='Fallback zone when no city matches.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shipping_shippingzone',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery failed'), ('RETURNED', 'Returned to sender')], default='PENDING', max_length=16)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.courier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.shippingmethod')),
            ],
            options={
                'db_table': 'shipping_shipment',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery failed'), ('RETURNED', 'Returned to sender')], max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment')),
            ],
            options={
                'db_table': 'shipping_shipmentevent',
                'ordering': ('occurred_at',),
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['order'], name='shipping_sh_order_i_cb7c84_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status', '-created_at'], name='shipping_sh_status_8a7968_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipping_sh_trackin_af3d4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='shipping_method_zone_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.00'))), name='shipping_method_price_gte_0'),
        ),
    ]
