# Generated by Django 5.1.15 on 2026-08-21 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Where this money came out of.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='finance.account'),
        ),
    ]
