# Generated by Django 5.1.15 on 2026-09-17 17:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productattributevalue"),
        ("purchasing", "0003_supplierpayment_idempotency_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_sku", models.CharField(blank=True, max_length=64)),
                (
                    "last_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("minimum_order_quantity", models.PositiveIntegerField(default=1)),
                ("is_preferred", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_purchased_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="purchasing.supplier",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_offers",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_supplierproduct",
                "ordering": ("-is_preferred", "last_cost"),
                "indexes": [
                    models.Index(
                        fields=["variant", "-is_preferred", "last_cost"],
                        name="purchasing__variant_a5a11e_idx",
                    ),
                    models.Index(
                        fields=["supplier", "-last_purchased_at"],
                        name="purchasing__supplie_60dc50_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "variant"),
                        name="purchasing_supplierproduct_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_preferred", True)),
                        fields=("variant",),
                        name="purchasing_supplierproduct_one_preferred",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_cost__gte", Decimal("0.00"))),
                        name="purchasing_supplierproduct_cost_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minimum_order_quantity__gte", 1)),
                        name="purchasing_supplierproduct_moq_gte_1",
                    ),
                ],
            },
        ),
    ]
