# Generated by Django 5.1.15 on 2026-09-18 03:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productattributevalue"),
        ("purchasing", "0004_supplierproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged in transit"),
                            ("DEFECTIVE", "Faulty goods"),
                            ("WRONG_ITEM", "Wrong item delivered"),
                            ("OVER_DELIVERED", "More than was ordered"),
                            ("EXPIRED", "Expired or short-dated"),
                            ("OTHER", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("returned_at", models.DateTimeField()),
                (
                    "credit_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=80, null=True, unique=True),
                ),
            ],
            options={
                "db_table": "purchasing_purchasereturn",
                "ordering": ("-returned_at",),
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_purchasereturnitem",
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="credited_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="quantity_returned",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_returned__lte", models.F("quantity_received"))
                ),
                name="purchasing_poi_returned_lte_received",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to="purchasing.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnitem",
            name="purchase_order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_items",
                to="purchasing.purchaseorderitem",
            ),
        ),
        migrations.AddField(
            model_name="purchasereturnitem",
            name="purchase_return",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="purchasing.purchasereturn",
            ),
        ),
        migrations.AddIndex(
            model_name="purchasereturn",
            index=models.Index(
                fields=["purchase_order", "-returned_at"],
                name="purchasing__purchas_7a9cfe_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_total__gte", Decimal("0.00"))),
                name="purchasing_purchasereturn_credit_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchasereturnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="purchasing_pri_return_qty_gt_0",
            ),
        ),
    ]
