# Generated by Django 5.1.5 on 2026-08-17 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, max_length=16)),
                ('last_value', models.BigIntegerField(default=0)),
                ('padding', models.PositiveSmallIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'number sequence',
                'db_table': 'core_numbersequence',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_setting',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('PERMISSION_ELEVATION', 'Permission elevation'), ('STOCK_ADJUSTMENT', 'Stock adjustment'), ('STOCK_TRANSFER', 'Stock transfer'), ('PURCHASE_RECEIVED', 'Purchase received'), ('SALE_CREATED', 'Sale created'), ('ORDER_STATUS_CHANGED', 'Order status changed'), ('ORDER_CANCELLED', 'Order cancelled'), ('PAYMENT_RECORDED', 'Payment recorded'), ('REFUND_ISSUED', 'Refund issued'), ('DISCOUNT_OVERRIDE', 'Discount override'), ('PRICE_OVERRIDE', 'Price override'), ('SETTINGS_CHANGED', 'Settings changed'), ('USER_CHANGED', 'User changed')], max_length=32)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.branch')),
            ],
            options={
                'db_table': 'core_auditlog',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='core_auditl_entity__1c230b_idx'), models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
