# Generated by Django 5.1.15 on 2026-08-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("LOGIN", "Login"),
                    ("LOGIN_FAILED", "Login failed"),
                    ("LOGOUT", "Logout"),
                    ("PERMISSION_ELEVATION", "Permission elevation"),
                    ("STOCK_ADJUSTMENT", "Stock adjustment"),
                    ("STOCK_TRANSFER", "Stock transfer"),
                    ("PURCHASE_RECEIVED", "Purchase received"),
                    ("SALE_CREATED", "Sale created"),
                    ("ORDER_STATUS_CHANGED", "Order status changed"),
                    ("ORDER_CANCELLED", "Order cancelled"),
                    ("PAYMENT_RECORDED", "Payment recorded"),
                    ("EXPENSE_RECORDED", "Expense recorded"),
                    ("EXPENSE_VOIDED", "Expense voided"),
                    ("REFUND_ISSUED", "Refund issued"),
                    ("DISCOUNT_OVERRIDE", "Discount override"),
                    ("PRICE_OVERRIDE", "Price override"),
                    ("SETTINGS_CHANGED", "Settings changed"),
                    ("USER_CHANGED", "User changed"),
                ],
                max_length=32,
            ),
        ),
    ]
