# Generated by Django 5.1.5 on 2026-08-17 17:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed amount'), ('FREE_SHIPPING', 'Free shipping')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0–100) or a fixed amount, depending on discount_type.', max_digits=10)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Caps a percentage discount.', max_digits=14, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total redemptions allowed. Null = unlimited.', null=True)),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('channels', models.JSONField(blank=True, default=list, help_text="Allowed channels, e.g. ['ONLINE']. Empty = all.")),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Restrict to these categories. Empty = whole catalogue.', related_name='coupons', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='catalog.product')),
            ],
            options={
                'db_table': 'promotions_coupon',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('released_at', models.DateTimeField(blank=True, help_text='Set when a cancelled order gives the usage back.', null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.coupon')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='orders.order')),
            ],
            options={
                'db_table': 'promotions_couponredemption',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', Decimal('0.00'))), name='promotions_coupon_value_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'PERCENTAGE'), _negated=True), ('value__lte', Decimal('100.00')), _connector='OR'), name='promotions_coupon_percentage_lte_100'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['coupon', 'customer'], name='promotions__coupon__52e524_idx'),
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'order'), name='promotions_redemption_uniq'),
        ),
    ]
