# Generated by Django 5.1.15 on 2026-08-28 08:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Let a FREE_SHIPPING coupon hold a value of 0.

    `value` meant "percent or fixed amount", and the old constraint demanded it
    be above zero for every coupon. A free-shipping coupon has no amount — its
    discount is the shipping line being zeroed in `checkout.price_cart` — so
    creating one meant inventing a number to satisfy a constraint that did not
    apply to it, and storing it to confuse the next reader.

    The constraint is only widened, so no existing row can violate it and no
    data migration is needed.
    """


    dependencies = [
        ("catalog", "0004_searchterm"),
        ("promotions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="coupon",
            name="promotions_coupon_value_gt_0",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percent (0–100) or a fixed amount, depending on discount_type. Always 0 for FREE_SHIPPING, which carries no amount.",
                max_digits=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "FREE_SHIPPING"),
                    ("value__gt", Decimal("0.00")),
                    _connector="OR",
                ),
                name="promotions_coupon_value_gt_0",
            ),
        ),
    ]
