// GENERATED by `npm run db:pull` from a database Django has migrated.
// Do not edit: change the Django model, migrate, and pull again.
import { relations } from "drizzle-orm/relations";
import { djangoContentType, authPermission, authGroupPermissions, authGroup, accountsOrganization, accountsBranch, accountsPermission, accountsRolePermissions, accountsRole, accountsUser, accountsUserGroups, accountsUserUserPermissions, accountsStaffprofile, djangoAdminLog, catalogCategory, catalogBrand, catalogProduct, catalogSizechart, catalogAttribute, catalogAttributevalue, catalogCategoryattribute, catalogProductvariant, catalogVariantattributevalue, catalogProductimage, catalogProductattributevalue, catalogSizechartrow, contentNavigationitem, contentSitepage, contentSitesettings, contentHomecarouselitem, coreSetting, coreAuditlog, ordersOrderevent, ordersOrder, ordersCart, promotionsCoupon, customersCustomer, shippingCourier, shippingShipment, shippingShippingmethod, shippingShipmentevent, shippingShippingzone, purchasingPurchaseorder, purchasingSupplier, purchasingPurchasereceipt, purchasingPurchaseorderitem, purchasingPurchasereceiptitem, financeAccount, purchasingSupplierpayment, customersCustomeraddress, customersCustomernote, promotionsCouponCategories, promotionsCouponProducts, promotionsCouponredemption, ordersHeldsale, ordersPaymentevent, ordersPayment, ordersReturnrequest, ordersCartitem, ordersRefund, ordersOrderitem, ordersReturnitem, financeAccounttransaction, financeAccounttransfer, engagementWishlist, engagementWishlistitem, engagementReview, financeExpensecategory, djangoCeleryBeatClockedschedule, djangoCeleryBeatPeriodictask, djangoCeleryBeatCrontabschedule, djangoCeleryBeatIntervalschedule, djangoCeleryBeatSolarschedule, financeExpense, inventoryStocktransfer, inventoryStockcount, inventoryStocktransferitem, inventoryStockcountitem, inventoryInventory, inventoryInventorytransaction, inventoryLabelprint, notificationsNotification, ordersAbandonedcheckout, purchasingSupplierproduct, purchasingPurchasereturn, purchasingPurchasereturnitem, tokenBlacklistOutstandingtoken, tokenBlacklistBlacklistedtoken } from "./schema";

export const authPermissionRelations = relations(authPermission, ({one, many}) => ({
	djangoContentType: one(djangoContentType, {
		fields: [authPermission.contentTypeId],
		references: [djangoContentType.id]
	}),
	authGroupPermissions: many(authGroupPermissions),
	accountsUserUserPermissions: many(accountsUserUserPermissions),
}));

export const djangoContentTypeRelations = relations(djangoContentType, ({many}) => ({
	authPermissions: many(authPermission),
	djangoAdminLogs: many(djangoAdminLog),
}));

export const authGroupPermissionsRelations = relations(authGroupPermissions, ({one}) => ({
	authPermission: one(authPermission, {
		fields: [authGroupPermissions.permissionId],
		references: [authPermission.id]
	}),
	authGroup: one(authGroup, {
		fields: [authGroupPermissions.groupId],
		references: [authGroup.id]
	}),
}));

export const authGroupRelations = relations(authGroup, ({many}) => ({
	authGroupPermissions: many(authGroupPermissions),
	accountsUserGroups: many(accountsUserGroups),
}));

export const accountsBranchRelations = relations(accountsBranch, ({one, many}) => ({
	accountsOrganization: one(accountsOrganization, {
		fields: [accountsBranch.organizationId],
		references: [accountsOrganization.id]
	}),
	accountsUsers: many(accountsUser),
	coreAuditlogs: many(coreAuditlog),
	ordersCarts: many(ordersCart),
	purchasingPurchaseorders: many(purchasingPurchaseorder),
	ordersHeldsales: many(ordersHeldsale),
	ordersOrders: many(ordersOrder),
	financeAccounts: many(financeAccount),
	financeExpenses: many(financeExpense),
	inventoryStocktransfers_sourceBranchId: many(inventoryStocktransfer, {
		relationName: "inventoryStocktransfer_sourceBranchId_accountsBranch_id"
	}),
	inventoryStocktransfers_targetBranchId: many(inventoryStocktransfer, {
		relationName: "inventoryStocktransfer_targetBranchId_accountsBranch_id"
	}),
	inventoryStockcounts: many(inventoryStockcount),
	inventoryInventories: many(inventoryInventory),
	inventoryInventorytransactions: many(inventoryInventorytransaction),
	inventoryLabelprints: many(inventoryLabelprint),
	notificationsNotifications: many(notificationsNotification),
	ordersAbandonedcheckouts: many(ordersAbandonedcheckout),
}));

export const accountsOrganizationRelations = relations(accountsOrganization, ({one, many}) => ({
	accountsBranches: many(accountsBranch),
	accountsUsers: many(accountsUser, {
		relationName: "accountsUser_organizationId_accountsOrganization_id"
	}),
	accountsUser: one(accountsUser, {
		fields: [accountsOrganization.taxSettledById],
		references: [accountsUser.id],
		relationName: "accountsOrganization_taxSettledById_accountsUser_id"
	}),
}));

export const accountsRolePermissionsRelations = relations(accountsRolePermissions, ({one}) => ({
	accountsPermission: one(accountsPermission, {
		fields: [accountsRolePermissions.permissionId],
		references: [accountsPermission.id]
	}),
	accountsRole: one(accountsRole, {
		fields: [accountsRolePermissions.roleId],
		references: [accountsRole.id]
	}),
}));

export const accountsPermissionRelations = relations(accountsPermission, ({many}) => ({
	accountsRolePermissions: many(accountsRolePermissions),
}));

export const accountsRoleRelations = relations(accountsRole, ({many}) => ({
	accountsRolePermissions: many(accountsRolePermissions),
	accountsUsers: many(accountsUser),
}));

export const accountsUserRelations = relations(accountsUser, ({one, many}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [accountsUser.branchId],
		references: [accountsBranch.id]
	}),
	accountsOrganization: one(accountsOrganization, {
		fields: [accountsUser.organizationId],
		references: [accountsOrganization.id],
		relationName: "accountsUser_organizationId_accountsOrganization_id"
	}),
	accountsRole: one(accountsRole, {
		fields: [accountsUser.roleId],
		references: [accountsRole.id]
	}),
	accountsUserGroups: many(accountsUserGroups),
	accountsUserUserPermissions: many(accountsUserUserPermissions),
	accountsOrganizations: many(accountsOrganization, {
		relationName: "accountsOrganization_taxSettledById_accountsUser_id"
	}),
	accountsStaffprofiles_createdById: many(accountsStaffprofile, {
		relationName: "accountsStaffprofile_createdById_accountsUser_id"
	}),
	accountsStaffprofiles_userId: many(accountsStaffprofile, {
		relationName: "accountsStaffprofile_userId_accountsUser_id"
	}),
	djangoAdminLogs: many(djangoAdminLog),
	catalogProducts: many(catalogProduct),
	catalogSizecharts: many(catalogSizechart),
	contentSitepages: many(contentSitepage),
	contentSitesettings: many(contentSitesettings),
	contentHomecarouselitems: many(contentHomecarouselitem),
	coreSettings: many(coreSetting),
	coreAuditlogs: many(coreAuditlog),
	ordersOrderevents: many(ordersOrderevent),
	shippingShipments: many(shippingShipment),
	shippingShipmentevents: many(shippingShipmentevent),
	purchasingPurchaseorders: many(purchasingPurchaseorder),
	purchasingPurchasereceipts: many(purchasingPurchasereceipt),
	purchasingSupplierpayments: many(purchasingSupplierpayment),
	customersCustomers_createdById: many(customersCustomer, {
		relationName: "customersCustomer_createdById_accountsUser_id"
	}),
	customersCustomers_userId: many(customersCustomer, {
		relationName: "customersCustomer_userId_accountsUser_id"
	}),
	customersCustomernotes: many(customersCustomernote),
	promotionsCoupons: many(promotionsCoupon),
	ordersHeldsales: many(ordersHeldsale),
	ordersReturnrequests_approvedById: many(ordersReturnrequest, {
		relationName: "ordersReturnrequest_approvedById_accountsUser_id"
	}),
	ordersReturnrequests_requestedById: many(ordersReturnrequest, {
		relationName: "ordersReturnrequest_requestedById_accountsUser_id"
	}),
	ordersPayments: many(ordersPayment),
	ordersRefunds: many(ordersRefund),
	ordersOrders: many(ordersOrder),
	financeAccounttransactions: many(financeAccounttransaction),
	financeAccounttransfers: many(financeAccounttransfer),
	financeAccounts: many(financeAccount),
	engagementReviews: many(engagementReview),
	financeExpensecategories: many(financeExpensecategory),
	financeExpenses_createdById: many(financeExpense, {
		relationName: "financeExpense_createdById_accountsUser_id"
	}),
	financeExpenses_voidedById: many(financeExpense, {
		relationName: "financeExpense_voidedById_accountsUser_id"
	}),
	inventoryStocktransfers_createdById: many(inventoryStocktransfer, {
		relationName: "inventoryStocktransfer_createdById_accountsUser_id"
	}),
	inventoryStocktransfers_receivedById: many(inventoryStocktransfer, {
		relationName: "inventoryStocktransfer_receivedById_accountsUser_id"
	}),
	inventoryStockcounts_appliedById: many(inventoryStockcount, {
		relationName: "inventoryStockcount_appliedById_accountsUser_id"
	}),
	inventoryStockcounts_createdById: many(inventoryStockcount, {
		relationName: "inventoryStockcount_createdById_accountsUser_id"
	}),
	inventoryInventorytransactions: many(inventoryInventorytransaction),
	inventoryLabelprints: many(inventoryLabelprint),
	notificationsNotifications: many(notificationsNotification),
	purchasingSupplierproducts: many(purchasingSupplierproduct),
	purchasingPurchasereturns: many(purchasingPurchasereturn),
	tokenBlacklistOutstandingtokens: many(tokenBlacklistOutstandingtoken),
}));

export const accountsUserGroupsRelations = relations(accountsUserGroups, ({one}) => ({
	authGroup: one(authGroup, {
		fields: [accountsUserGroups.groupId],
		references: [authGroup.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [accountsUserGroups.userId],
		references: [accountsUser.id]
	}),
}));

export const accountsUserUserPermissionsRelations = relations(accountsUserUserPermissions, ({one}) => ({
	authPermission: one(authPermission, {
		fields: [accountsUserUserPermissions.permissionId],
		references: [authPermission.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [accountsUserUserPermissions.userId],
		references: [accountsUser.id]
	}),
}));

export const accountsStaffprofileRelations = relations(accountsStaffprofile, ({one}) => ({
	accountsUser_createdById: one(accountsUser, {
		fields: [accountsStaffprofile.createdById],
		references: [accountsUser.id],
		relationName: "accountsStaffprofile_createdById_accountsUser_id"
	}),
	accountsUser_userId: one(accountsUser, {
		fields: [accountsStaffprofile.userId],
		references: [accountsUser.id],
		relationName: "accountsStaffprofile_userId_accountsUser_id"
	}),
}));

export const djangoAdminLogRelations = relations(djangoAdminLog, ({one}) => ({
	djangoContentType: one(djangoContentType, {
		fields: [djangoAdminLog.contentTypeId],
		references: [djangoContentType.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [djangoAdminLog.userId],
		references: [accountsUser.id]
	}),
}));

export const catalogCategoryRelations = relations(catalogCategory, ({one, many}) => ({
	catalogCategory: one(catalogCategory, {
		fields: [catalogCategory.parentId],
		references: [catalogCategory.id],
		relationName: "catalogCategory_parentId_catalogCategory_id"
	}),
	catalogCategories: many(catalogCategory, {
		relationName: "catalogCategory_parentId_catalogCategory_id"
	}),
	catalogProducts: many(catalogProduct),
	catalogCategoryattributes: many(catalogCategoryattribute),
	contentNavigationitems: many(contentNavigationitem),
	promotionsCouponCategories: many(promotionsCouponCategories),
}));

export const catalogProductRelations = relations(catalogProduct, ({one, many}) => ({
	catalogBrand: one(catalogBrand, {
		fields: [catalogProduct.brandId],
		references: [catalogBrand.id]
	}),
	catalogCategory: one(catalogCategory, {
		fields: [catalogProduct.categoryId],
		references: [catalogCategory.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [catalogProduct.createdById],
		references: [accountsUser.id]
	}),
	catalogSizechart: one(catalogSizechart, {
		fields: [catalogProduct.sizeChartId],
		references: [catalogSizechart.id]
	}),
	catalogProductvariants: many(catalogProductvariant),
	catalogProductimages: many(catalogProductimage),
	catalogProductattributevalues: many(catalogProductattributevalue),
	contentHomecarouselitems: many(contentHomecarouselitem),
	promotionsCouponProducts: many(promotionsCouponProducts),
	engagementWishlistitems: many(engagementWishlistitem),
	engagementReviews: many(engagementReview),
}));

export const catalogBrandRelations = relations(catalogBrand, ({many}) => ({
	catalogProducts: many(catalogProduct),
}));

export const catalogSizechartRelations = relations(catalogSizechart, ({one, many}) => ({
	catalogProducts: many(catalogProduct),
	catalogAttribute: one(catalogAttribute, {
		fields: [catalogSizechart.attributeId],
		references: [catalogAttribute.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [catalogSizechart.createdById],
		references: [accountsUser.id]
	}),
	catalogSizechartrows: many(catalogSizechartrow),
}));

export const catalogAttributevalueRelations = relations(catalogAttributevalue, ({one, many}) => ({
	catalogAttribute: one(catalogAttribute, {
		fields: [catalogAttributevalue.attributeId],
		references: [catalogAttribute.id]
	}),
	catalogVariantattributevalues: many(catalogVariantattributevalue),
	catalogProductimages: many(catalogProductimage),
	catalogProductattributevalues: many(catalogProductattributevalue),
	catalogSizechartrows: many(catalogSizechartrow),
}));

export const catalogAttributeRelations = relations(catalogAttribute, ({many}) => ({
	catalogAttributevalues: many(catalogAttributevalue),
	catalogCategoryattributes: many(catalogCategoryattribute),
	catalogVariantattributevalues: many(catalogVariantattributevalue),
	catalogSizecharts: many(catalogSizechart),
}));

export const catalogCategoryattributeRelations = relations(catalogCategoryattribute, ({one}) => ({
	catalogAttribute: one(catalogAttribute, {
		fields: [catalogCategoryattribute.attributeId],
		references: [catalogAttribute.id]
	}),
	catalogCategory: one(catalogCategory, {
		fields: [catalogCategoryattribute.categoryId],
		references: [catalogCategory.id]
	}),
}));

export const catalogProductvariantRelations = relations(catalogProductvariant, ({one, many}) => ({
	catalogProduct: one(catalogProduct, {
		fields: [catalogProductvariant.productId],
		references: [catalogProduct.id]
	}),
	catalogVariantattributevalues: many(catalogVariantattributevalue),
	purchasingPurchaseorderitems: many(purchasingPurchaseorderitem),
	ordersCartitems: many(ordersCartitem),
	ordersOrderitems: many(ordersOrderitem),
	engagementWishlistitems: many(engagementWishlistitem),
	inventoryStocktransferitems: many(inventoryStocktransferitem),
	inventoryStockcountitems: many(inventoryStockcountitem),
	inventoryInventories: many(inventoryInventory),
	inventoryInventorytransactions: many(inventoryInventorytransaction),
	inventoryLabelprints: many(inventoryLabelprint),
	purchasingSupplierproducts: many(purchasingSupplierproduct),
}));

export const catalogVariantattributevalueRelations = relations(catalogVariantattributevalue, ({one}) => ({
	catalogAttribute: one(catalogAttribute, {
		fields: [catalogVariantattributevalue.attributeId],
		references: [catalogAttribute.id]
	}),
	catalogAttributevalue: one(catalogAttributevalue, {
		fields: [catalogVariantattributevalue.attributeValueId],
		references: [catalogAttributevalue.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [catalogVariantattributevalue.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const catalogProductimageRelations = relations(catalogProductimage, ({one}) => ({
	catalogAttributevalue: one(catalogAttributevalue, {
		fields: [catalogProductimage.attributeValueId],
		references: [catalogAttributevalue.id]
	}),
	catalogProduct: one(catalogProduct, {
		fields: [catalogProductimage.productId],
		references: [catalogProduct.id]
	}),
}));

export const catalogProductattributevalueRelations = relations(catalogProductattributevalue, ({one}) => ({
	catalogAttributevalue: one(catalogAttributevalue, {
		fields: [catalogProductattributevalue.attributeValueId],
		references: [catalogAttributevalue.id]
	}),
	catalogProduct: one(catalogProduct, {
		fields: [catalogProductattributevalue.productId],
		references: [catalogProduct.id]
	}),
}));

export const catalogSizechartrowRelations = relations(catalogSizechartrow, ({one}) => ({
	catalogAttributevalue: one(catalogAttributevalue, {
		fields: [catalogSizechartrow.attributeValueId],
		references: [catalogAttributevalue.id]
	}),
	catalogSizechart: one(catalogSizechart, {
		fields: [catalogSizechartrow.chartId],
		references: [catalogSizechart.id]
	}),
}));

export const contentNavigationitemRelations = relations(contentNavigationitem, ({one, many}) => ({
	catalogCategory: one(catalogCategory, {
		fields: [contentNavigationitem.categoryId],
		references: [catalogCategory.id]
	}),
	contentNavigationitem: one(contentNavigationitem, {
		fields: [contentNavigationitem.parentId],
		references: [contentNavigationitem.id],
		relationName: "contentNavigationitem_parentId_contentNavigationitem_id"
	}),
	contentNavigationitems: many(contentNavigationitem, {
		relationName: "contentNavigationitem_parentId_contentNavigationitem_id"
	}),
	contentSitepage: one(contentSitepage, {
		fields: [contentNavigationitem.pageId],
		references: [contentSitepage.id]
	}),
}));

export const contentSitepageRelations = relations(contentSitepage, ({one, many}) => ({
	contentNavigationitems: many(contentNavigationitem),
	accountsUser: one(accountsUser, {
		fields: [contentSitepage.updatedById],
		references: [accountsUser.id]
	}),
}));

export const contentSitesettingsRelations = relations(contentSitesettings, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [contentSitesettings.updatedById],
		references: [accountsUser.id]
	}),
}));

export const contentHomecarouselitemRelations = relations(contentHomecarouselitem, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [contentHomecarouselitem.createdById],
		references: [accountsUser.id]
	}),
	catalogProduct: one(catalogProduct, {
		fields: [contentHomecarouselitem.productId],
		references: [catalogProduct.id]
	}),
}));

export const coreSettingRelations = relations(coreSetting, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [coreSetting.updatedById],
		references: [accountsUser.id]
	}),
}));

export const coreAuditlogRelations = relations(coreAuditlog, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [coreAuditlog.actorId],
		references: [accountsUser.id]
	}),
	accountsBranch: one(accountsBranch, {
		fields: [coreAuditlog.branchId],
		references: [accountsBranch.id]
	}),
}));

export const ordersOrdereventRelations = relations(ordersOrderevent, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [ordersOrderevent.actorId],
		references: [accountsUser.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [ordersOrderevent.orderId],
		references: [ordersOrder.id]
	}),
}));

export const ordersOrderRelations = relations(ordersOrder, ({one, many}) => ({
	ordersOrderevents: many(ordersOrderevent),
	shippingShipments: many(shippingShipment),
	promotionsCouponredemptions: many(promotionsCouponredemption),
	ordersPaymentevents: many(ordersPaymentevent),
	ordersReturnrequests: many(ordersReturnrequest),
	ordersPayments: many(ordersPayment),
	ordersRefunds: many(ordersRefund),
	ordersOrderitems: many(ordersOrderitem),
	accountsBranch: one(accountsBranch, {
		fields: [ordersOrder.branchId],
		references: [accountsBranch.id]
	}),
	promotionsCoupon: one(promotionsCoupon, {
		fields: [ordersOrder.couponId],
		references: [promotionsCoupon.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [ordersOrder.createdById],
		references: [accountsUser.id]
	}),
	customersCustomer: one(customersCustomer, {
		fields: [ordersOrder.customerId],
		references: [customersCustomer.id]
	}),
	shippingShippingmethod: one(shippingShippingmethod, {
		fields: [ordersOrder.shippingMethodId],
		references: [shippingShippingmethod.id]
	}),
	engagementReviews: many(engagementReview),
	ordersAbandonedcheckouts: many(ordersAbandonedcheckout),
}));

export const ordersCartRelations = relations(ordersCart, ({one, many}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [ordersCart.branchId],
		references: [accountsBranch.id]
	}),
	promotionsCoupon: one(promotionsCoupon, {
		fields: [ordersCart.couponId],
		references: [promotionsCoupon.id]
	}),
	customersCustomer: one(customersCustomer, {
		fields: [ordersCart.customerId],
		references: [customersCustomer.id]
	}),
	ordersCartitems: many(ordersCartitem),
	ordersAbandonedcheckouts: many(ordersAbandonedcheckout),
}));

export const promotionsCouponRelations = relations(promotionsCoupon, ({one, many}) => ({
	ordersCarts: many(ordersCart),
	accountsUser: one(accountsUser, {
		fields: [promotionsCoupon.createdById],
		references: [accountsUser.id]
	}),
	promotionsCouponCategories: many(promotionsCouponCategories),
	promotionsCouponProducts: many(promotionsCouponProducts),
	promotionsCouponredemptions: many(promotionsCouponredemption),
	ordersOrders: many(ordersOrder),
}));

export const customersCustomerRelations = relations(customersCustomer, ({one, many}) => ({
	ordersCarts: many(ordersCart),
	accountsUser_createdById: one(accountsUser, {
		fields: [customersCustomer.createdById],
		references: [accountsUser.id],
		relationName: "customersCustomer_createdById_accountsUser_id"
	}),
	accountsUser_userId: one(accountsUser, {
		fields: [customersCustomer.userId],
		references: [accountsUser.id],
		relationName: "customersCustomer_userId_accountsUser_id"
	}),
	customersCustomeraddresses: many(customersCustomeraddress),
	customersCustomernotes: many(customersCustomernote),
	promotionsCouponredemptions: many(promotionsCouponredemption),
	ordersHeldsales: many(ordersHeldsale),
	ordersOrders: many(ordersOrder),
	engagementWishlists: many(engagementWishlist),
	engagementReviews: many(engagementReview),
	ordersAbandonedcheckouts: many(ordersAbandonedcheckout),
}));

export const shippingShipmentRelations = relations(shippingShipment, ({one, many}) => ({
	shippingCourier: one(shippingCourier, {
		fields: [shippingShipment.courierId],
		references: [shippingCourier.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [shippingShipment.createdById],
		references: [accountsUser.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [shippingShipment.orderId],
		references: [ordersOrder.id]
	}),
	shippingShippingmethod: one(shippingShippingmethod, {
		fields: [shippingShipment.shippingMethodId],
		references: [shippingShippingmethod.id]
	}),
	shippingShipmentevents: many(shippingShipmentevent),
}));

export const shippingCourierRelations = relations(shippingCourier, ({many}) => ({
	shippingShipments: many(shippingShipment),
}));

export const shippingShippingmethodRelations = relations(shippingShippingmethod, ({one, many}) => ({
	shippingShipments: many(shippingShipment),
	shippingShippingzone: one(shippingShippingzone, {
		fields: [shippingShippingmethod.zoneId],
		references: [shippingShippingzone.id]
	}),
	ordersOrders: many(ordersOrder),
}));

export const shippingShipmenteventRelations = relations(shippingShipmentevent, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [shippingShipmentevent.createdById],
		references: [accountsUser.id]
	}),
	shippingShipment: one(shippingShipment, {
		fields: [shippingShipmentevent.shipmentId],
		references: [shippingShipment.id]
	}),
}));

export const shippingShippingzoneRelations = relations(shippingShippingzone, ({many}) => ({
	shippingShippingmethods: many(shippingShippingmethod),
}));

export const purchasingPurchaseorderRelations = relations(purchasingPurchaseorder, ({one, many}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [purchasingPurchaseorder.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [purchasingPurchaseorder.createdById],
		references: [accountsUser.id]
	}),
	purchasingSupplier: one(purchasingSupplier, {
		fields: [purchasingPurchaseorder.supplierId],
		references: [purchasingSupplier.id]
	}),
	purchasingPurchasereceipts: many(purchasingPurchasereceipt),
	purchasingSupplierpayments: many(purchasingSupplierpayment),
	purchasingPurchaseorderitems: many(purchasingPurchaseorderitem),
	purchasingPurchasereturns: many(purchasingPurchasereturn),
}));

export const purchasingSupplierRelations = relations(purchasingSupplier, ({many}) => ({
	purchasingPurchaseorders: many(purchasingPurchaseorder),
	purchasingSupplierpayments: many(purchasingSupplierpayment),
	purchasingSupplierproducts: many(purchasingSupplierproduct),
}));

export const purchasingPurchasereceiptRelations = relations(purchasingPurchasereceipt, ({one, many}) => ({
	purchasingPurchaseorder: one(purchasingPurchaseorder, {
		fields: [purchasingPurchasereceipt.purchaseOrderId],
		references: [purchasingPurchaseorder.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [purchasingPurchasereceipt.receivedById],
		references: [accountsUser.id]
	}),
	purchasingPurchasereceiptitems: many(purchasingPurchasereceiptitem),
}));

export const purchasingPurchasereceiptitemRelations = relations(purchasingPurchasereceiptitem, ({one}) => ({
	purchasingPurchaseorderitem: one(purchasingPurchaseorderitem, {
		fields: [purchasingPurchasereceiptitem.purchaseOrderItemId],
		references: [purchasingPurchaseorderitem.id]
	}),
	purchasingPurchasereceipt: one(purchasingPurchasereceipt, {
		fields: [purchasingPurchasereceiptitem.receiptId],
		references: [purchasingPurchasereceipt.id]
	}),
}));

export const purchasingPurchaseorderitemRelations = relations(purchasingPurchaseorderitem, ({one, many}) => ({
	purchasingPurchasereceiptitems: many(purchasingPurchasereceiptitem),
	purchasingPurchaseorder: one(purchasingPurchaseorder, {
		fields: [purchasingPurchaseorderitem.purchaseOrderId],
		references: [purchasingPurchaseorder.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [purchasingPurchaseorderitem.variantId],
		references: [catalogProductvariant.id]
	}),
	purchasingPurchasereturnitems: many(purchasingPurchasereturnitem),
}));

export const purchasingSupplierpaymentRelations = relations(purchasingSupplierpayment, ({one}) => ({
	financeAccount: one(financeAccount, {
		fields: [purchasingSupplierpayment.accountId],
		references: [financeAccount.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [purchasingSupplierpayment.createdById],
		references: [accountsUser.id]
	}),
	purchasingPurchaseorder: one(purchasingPurchaseorder, {
		fields: [purchasingSupplierpayment.purchaseOrderId],
		references: [purchasingPurchaseorder.id]
	}),
	purchasingSupplier: one(purchasingSupplier, {
		fields: [purchasingSupplierpayment.supplierId],
		references: [purchasingSupplier.id]
	}),
}));

export const financeAccountRelations = relations(financeAccount, ({one, many}) => ({
	purchasingSupplierpayments: many(purchasingSupplierpayment),
	ordersPayments: many(ordersPayment),
	ordersRefunds: many(ordersRefund),
	financeAccounttransactions: many(financeAccounttransaction),
	financeAccounttransfers_sourceAccountId: many(financeAccounttransfer, {
		relationName: "financeAccounttransfer_sourceAccountId_financeAccount_id"
	}),
	financeAccounttransfers_targetAccountId: many(financeAccounttransfer, {
		relationName: "financeAccounttransfer_targetAccountId_financeAccount_id"
	}),
	accountsBranch: one(accountsBranch, {
		fields: [financeAccount.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [financeAccount.createdById],
		references: [accountsUser.id]
	}),
	financeExpenses: many(financeExpense),
}));

export const customersCustomeraddressRelations = relations(customersCustomeraddress, ({one}) => ({
	customersCustomer: one(customersCustomer, {
		fields: [customersCustomeraddress.customerId],
		references: [customersCustomer.id]
	}),
}));

export const customersCustomernoteRelations = relations(customersCustomernote, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [customersCustomernote.createdById],
		references: [accountsUser.id]
	}),
	customersCustomer: one(customersCustomer, {
		fields: [customersCustomernote.customerId],
		references: [customersCustomer.id]
	}),
}));

export const promotionsCouponCategoriesRelations = relations(promotionsCouponCategories, ({one}) => ({
	catalogCategory: one(catalogCategory, {
		fields: [promotionsCouponCategories.categoryId],
		references: [catalogCategory.id]
	}),
	promotionsCoupon: one(promotionsCoupon, {
		fields: [promotionsCouponCategories.couponId],
		references: [promotionsCoupon.id]
	}),
}));

export const promotionsCouponProductsRelations = relations(promotionsCouponProducts, ({one}) => ({
	promotionsCoupon: one(promotionsCoupon, {
		fields: [promotionsCouponProducts.couponId],
		references: [promotionsCoupon.id]
	}),
	catalogProduct: one(catalogProduct, {
		fields: [promotionsCouponProducts.productId],
		references: [catalogProduct.id]
	}),
}));

export const promotionsCouponredemptionRelations = relations(promotionsCouponredemption, ({one}) => ({
	promotionsCoupon: one(promotionsCoupon, {
		fields: [promotionsCouponredemption.couponId],
		references: [promotionsCoupon.id]
	}),
	customersCustomer: one(customersCustomer, {
		fields: [promotionsCouponredemption.customerId],
		references: [customersCustomer.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [promotionsCouponredemption.orderId],
		references: [ordersOrder.id]
	}),
}));

export const ordersHeldsaleRelations = relations(ordersHeldsale, ({one}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [ordersHeldsale.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [ordersHeldsale.createdById],
		references: [accountsUser.id]
	}),
	customersCustomer: one(customersCustomer, {
		fields: [ordersHeldsale.customerId],
		references: [customersCustomer.id]
	}),
}));

export const ordersPaymenteventRelations = relations(ordersPaymentevent, ({one}) => ({
	ordersOrder: one(ordersOrder, {
		fields: [ordersPaymentevent.orderId],
		references: [ordersOrder.id]
	}),
	ordersPayment: one(ordersPayment, {
		fields: [ordersPaymentevent.paymentId],
		references: [ordersPayment.id]
	}),
}));

export const ordersPaymentRelations = relations(ordersPayment, ({one, many}) => ({
	ordersPaymentevents: many(ordersPaymentevent),
	financeAccount: one(financeAccount, {
		fields: [ordersPayment.accountId],
		references: [financeAccount.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [ordersPayment.createdById],
		references: [accountsUser.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [ordersPayment.orderId],
		references: [ordersOrder.id]
	}),
	ordersRefunds: many(ordersRefund),
}));

export const ordersReturnrequestRelations = relations(ordersReturnrequest, ({one, many}) => ({
	accountsUser_approvedById: one(accountsUser, {
		fields: [ordersReturnrequest.approvedById],
		references: [accountsUser.id],
		relationName: "ordersReturnrequest_approvedById_accountsUser_id"
	}),
	ordersOrder: one(ordersOrder, {
		fields: [ordersReturnrequest.orderId],
		references: [ordersOrder.id]
	}),
	accountsUser_requestedById: one(accountsUser, {
		fields: [ordersReturnrequest.requestedById],
		references: [accountsUser.id],
		relationName: "ordersReturnrequest_requestedById_accountsUser_id"
	}),
	ordersRefunds: many(ordersRefund),
	ordersReturnitems: many(ordersReturnitem),
}));

export const ordersCartitemRelations = relations(ordersCartitem, ({one}) => ({
	ordersCart: one(ordersCart, {
		fields: [ordersCartitem.cartId],
		references: [ordersCart.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [ordersCartitem.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const ordersRefundRelations = relations(ordersRefund, ({one}) => ({
	financeAccount: one(financeAccount, {
		fields: [ordersRefund.accountId],
		references: [financeAccount.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [ordersRefund.createdById],
		references: [accountsUser.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [ordersRefund.orderId],
		references: [ordersOrder.id]
	}),
	ordersPayment: one(ordersPayment, {
		fields: [ordersRefund.paymentId],
		references: [ordersPayment.id]
	}),
	ordersReturnrequest: one(ordersReturnrequest, {
		fields: [ordersRefund.returnRequestId],
		references: [ordersReturnrequest.id]
	}),
}));

export const ordersOrderitemRelations = relations(ordersOrderitem, ({one, many}) => ({
	ordersOrder: one(ordersOrder, {
		fields: [ordersOrderitem.orderId],
		references: [ordersOrder.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [ordersOrderitem.variantId],
		references: [catalogProductvariant.id]
	}),
	ordersReturnitems: many(ordersReturnitem),
}));

export const ordersReturnitemRelations = relations(ordersReturnitem, ({one}) => ({
	ordersOrderitem: one(ordersOrderitem, {
		fields: [ordersReturnitem.orderItemId],
		references: [ordersOrderitem.id]
	}),
	ordersReturnrequest: one(ordersReturnrequest, {
		fields: [ordersReturnitem.returnRequestId],
		references: [ordersReturnrequest.id]
	}),
}));

export const financeAccounttransactionRelations = relations(financeAccounttransaction, ({one, many}) => ({
	financeAccount: one(financeAccount, {
		fields: [financeAccounttransaction.accountId],
		references: [financeAccount.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [financeAccounttransaction.createdById],
		references: [accountsUser.id]
	}),
	financeExpenses_reversalId: many(financeExpense, {
		relationName: "financeExpense_reversalId_financeAccounttransaction_id"
	}),
	financeExpenses_transactionId: many(financeExpense, {
		relationName: "financeExpense_transactionId_financeAccounttransaction_id"
	}),
}));

export const financeAccounttransferRelations = relations(financeAccounttransfer, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [financeAccounttransfer.createdById],
		references: [accountsUser.id]
	}),
	financeAccount_sourceAccountId: one(financeAccount, {
		fields: [financeAccounttransfer.sourceAccountId],
		references: [financeAccount.id],
		relationName: "financeAccounttransfer_sourceAccountId_financeAccount_id"
	}),
	financeAccount_targetAccountId: one(financeAccount, {
		fields: [financeAccounttransfer.targetAccountId],
		references: [financeAccount.id],
		relationName: "financeAccounttransfer_targetAccountId_financeAccount_id"
	}),
}));

export const engagementWishlistRelations = relations(engagementWishlist, ({one, many}) => ({
	customersCustomer: one(customersCustomer, {
		fields: [engagementWishlist.customerId],
		references: [customersCustomer.id]
	}),
	engagementWishlistitems: many(engagementWishlistitem),
}));

export const engagementWishlistitemRelations = relations(engagementWishlistitem, ({one}) => ({
	catalogProduct: one(catalogProduct, {
		fields: [engagementWishlistitem.productId],
		references: [catalogProduct.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [engagementWishlistitem.variantId],
		references: [catalogProductvariant.id]
	}),
	engagementWishlist: one(engagementWishlist, {
		fields: [engagementWishlistitem.wishlistId],
		references: [engagementWishlist.id]
	}),
}));

export const engagementReviewRelations = relations(engagementReview, ({one}) => ({
	customersCustomer: one(customersCustomer, {
		fields: [engagementReview.customerId],
		references: [customersCustomer.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [engagementReview.moderatedById],
		references: [accountsUser.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [engagementReview.orderId],
		references: [ordersOrder.id]
	}),
	catalogProduct: one(catalogProduct, {
		fields: [engagementReview.productId],
		references: [catalogProduct.id]
	}),
}));

export const financeExpensecategoryRelations = relations(financeExpensecategory, ({one, many}) => ({
	accountsUser: one(accountsUser, {
		fields: [financeExpensecategory.createdById],
		references: [accountsUser.id]
	}),
	financeExpenses: many(financeExpense),
}));

export const djangoCeleryBeatPeriodictaskRelations = relations(djangoCeleryBeatPeriodictask, ({one}) => ({
	djangoCeleryBeatClockedschedule: one(djangoCeleryBeatClockedschedule, {
		fields: [djangoCeleryBeatPeriodictask.clockedId],
		references: [djangoCeleryBeatClockedschedule.id]
	}),
	djangoCeleryBeatCrontabschedule: one(djangoCeleryBeatCrontabschedule, {
		fields: [djangoCeleryBeatPeriodictask.crontabId],
		references: [djangoCeleryBeatCrontabschedule.id]
	}),
	djangoCeleryBeatIntervalschedule: one(djangoCeleryBeatIntervalschedule, {
		fields: [djangoCeleryBeatPeriodictask.intervalId],
		references: [djangoCeleryBeatIntervalschedule.id]
	}),
	djangoCeleryBeatSolarschedule: one(djangoCeleryBeatSolarschedule, {
		fields: [djangoCeleryBeatPeriodictask.solarId],
		references: [djangoCeleryBeatSolarschedule.id]
	}),
}));

export const djangoCeleryBeatClockedscheduleRelations = relations(djangoCeleryBeatClockedschedule, ({many}) => ({
	djangoCeleryBeatPeriodictasks: many(djangoCeleryBeatPeriodictask),
}));

export const djangoCeleryBeatCrontabscheduleRelations = relations(djangoCeleryBeatCrontabschedule, ({many}) => ({
	djangoCeleryBeatPeriodictasks: many(djangoCeleryBeatPeriodictask),
}));

export const djangoCeleryBeatIntervalscheduleRelations = relations(djangoCeleryBeatIntervalschedule, ({many}) => ({
	djangoCeleryBeatPeriodictasks: many(djangoCeleryBeatPeriodictask),
}));

export const djangoCeleryBeatSolarscheduleRelations = relations(djangoCeleryBeatSolarschedule, ({many}) => ({
	djangoCeleryBeatPeriodictasks: many(djangoCeleryBeatPeriodictask),
}));

export const financeExpenseRelations = relations(financeExpense, ({one}) => ({
	financeAccount: one(financeAccount, {
		fields: [financeExpense.accountId],
		references: [financeAccount.id]
	}),
	accountsBranch: one(accountsBranch, {
		fields: [financeExpense.branchId],
		references: [accountsBranch.id]
	}),
	financeExpensecategory: one(financeExpensecategory, {
		fields: [financeExpense.categoryId],
		references: [financeExpensecategory.id]
	}),
	accountsUser_createdById: one(accountsUser, {
		fields: [financeExpense.createdById],
		references: [accountsUser.id],
		relationName: "financeExpense_createdById_accountsUser_id"
	}),
	financeAccounttransaction_reversalId: one(financeAccounttransaction, {
		fields: [financeExpense.reversalId],
		references: [financeAccounttransaction.id],
		relationName: "financeExpense_reversalId_financeAccounttransaction_id"
	}),
	financeAccounttransaction_transactionId: one(financeAccounttransaction, {
		fields: [financeExpense.transactionId],
		references: [financeAccounttransaction.id],
		relationName: "financeExpense_transactionId_financeAccounttransaction_id"
	}),
	accountsUser_voidedById: one(accountsUser, {
		fields: [financeExpense.voidedById],
		references: [accountsUser.id],
		relationName: "financeExpense_voidedById_accountsUser_id"
	}),
}));

export const inventoryStocktransferRelations = relations(inventoryStocktransfer, ({one, many}) => ({
	accountsUser_createdById: one(accountsUser, {
		fields: [inventoryStocktransfer.createdById],
		references: [accountsUser.id],
		relationName: "inventoryStocktransfer_createdById_accountsUser_id"
	}),
	accountsUser_receivedById: one(accountsUser, {
		fields: [inventoryStocktransfer.receivedById],
		references: [accountsUser.id],
		relationName: "inventoryStocktransfer_receivedById_accountsUser_id"
	}),
	accountsBranch_sourceBranchId: one(accountsBranch, {
		fields: [inventoryStocktransfer.sourceBranchId],
		references: [accountsBranch.id],
		relationName: "inventoryStocktransfer_sourceBranchId_accountsBranch_id"
	}),
	accountsBranch_targetBranchId: one(accountsBranch, {
		fields: [inventoryStocktransfer.targetBranchId],
		references: [accountsBranch.id],
		relationName: "inventoryStocktransfer_targetBranchId_accountsBranch_id"
	}),
	inventoryStocktransferitems: many(inventoryStocktransferitem),
}));

export const inventoryStockcountRelations = relations(inventoryStockcount, ({one, many}) => ({
	accountsUser_appliedById: one(accountsUser, {
		fields: [inventoryStockcount.appliedById],
		references: [accountsUser.id],
		relationName: "inventoryStockcount_appliedById_accountsUser_id"
	}),
	accountsBranch: one(accountsBranch, {
		fields: [inventoryStockcount.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser_createdById: one(accountsUser, {
		fields: [inventoryStockcount.createdById],
		references: [accountsUser.id],
		relationName: "inventoryStockcount_createdById_accountsUser_id"
	}),
	inventoryStockcountitems: many(inventoryStockcountitem),
}));

export const inventoryStocktransferitemRelations = relations(inventoryStocktransferitem, ({one}) => ({
	inventoryStocktransfer: one(inventoryStocktransfer, {
		fields: [inventoryStocktransferitem.transferId],
		references: [inventoryStocktransfer.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [inventoryStocktransferitem.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const inventoryStockcountitemRelations = relations(inventoryStockcountitem, ({one}) => ({
	inventoryStockcount: one(inventoryStockcount, {
		fields: [inventoryStockcountitem.stockCountId],
		references: [inventoryStockcount.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [inventoryStockcountitem.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const inventoryInventoryRelations = relations(inventoryInventory, ({one}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [inventoryInventory.branchId],
		references: [accountsBranch.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [inventoryInventory.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const inventoryInventorytransactionRelations = relations(inventoryInventorytransaction, ({one}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [inventoryInventorytransaction.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [inventoryInventorytransaction.createdById],
		references: [accountsUser.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [inventoryInventorytransaction.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const inventoryLabelprintRelations = relations(inventoryLabelprint, ({one}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [inventoryLabelprint.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [inventoryLabelprint.createdById],
		references: [accountsUser.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [inventoryLabelprint.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const notificationsNotificationRelations = relations(notificationsNotification, ({one}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [notificationsNotification.branchId],
		references: [accountsBranch.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [notificationsNotification.userId],
		references: [accountsUser.id]
	}),
}));

export const ordersAbandonedcheckoutRelations = relations(ordersAbandonedcheckout, ({one}) => ({
	accountsBranch: one(accountsBranch, {
		fields: [ordersAbandonedcheckout.branchId],
		references: [accountsBranch.id]
	}),
	customersCustomer: one(customersCustomer, {
		fields: [ordersAbandonedcheckout.customerId],
		references: [customersCustomer.id]
	}),
	ordersOrder: one(ordersOrder, {
		fields: [ordersAbandonedcheckout.recoveredOrderId],
		references: [ordersOrder.id]
	}),
	ordersCart: one(ordersCart, {
		fields: [ordersAbandonedcheckout.cartId],
		references: [ordersCart.id]
	}),
}));

export const purchasingSupplierproductRelations = relations(purchasingSupplierproduct, ({one}) => ({
	accountsUser: one(accountsUser, {
		fields: [purchasingSupplierproduct.createdById],
		references: [accountsUser.id]
	}),
	purchasingSupplier: one(purchasingSupplier, {
		fields: [purchasingSupplierproduct.supplierId],
		references: [purchasingSupplier.id]
	}),
	catalogProductvariant: one(catalogProductvariant, {
		fields: [purchasingSupplierproduct.variantId],
		references: [catalogProductvariant.id]
	}),
}));

export const purchasingPurchasereturnRelations = relations(purchasingPurchasereturn, ({one, many}) => ({
	purchasingPurchaseorder: one(purchasingPurchaseorder, {
		fields: [purchasingPurchasereturn.purchaseOrderId],
		references: [purchasingPurchaseorder.id]
	}),
	accountsUser: one(accountsUser, {
		fields: [purchasingPurchasereturn.returnedById],
		references: [accountsUser.id]
	}),
	purchasingPurchasereturnitems: many(purchasingPurchasereturnitem),
}));

export const purchasingPurchasereturnitemRelations = relations(purchasingPurchasereturnitem, ({one}) => ({
	purchasingPurchaseorderitem: one(purchasingPurchaseorderitem, {
		fields: [purchasingPurchasereturnitem.purchaseOrderItemId],
		references: [purchasingPurchaseorderitem.id]
	}),
	purchasingPurchasereturn: one(purchasingPurchasereturn, {
		fields: [purchasingPurchasereturnitem.purchaseReturnId],
		references: [purchasingPurchasereturn.id]
	}),
}));

export const tokenBlacklistOutstandingtokenRelations = relations(tokenBlacklistOutstandingtoken, ({one, many}) => ({
	accountsUser: one(accountsUser, {
		fields: [tokenBlacklistOutstandingtoken.userId],
		references: [accountsUser.id]
	}),
	tokenBlacklistBlacklistedtokens: many(tokenBlacklistBlacklistedtoken),
}));

export const tokenBlacklistBlacklistedtokenRelations = relations(tokenBlacklistBlacklistedtoken, ({one}) => ({
	tokenBlacklistOutstandingtoken: one(tokenBlacklistOutstandingtoken, {
		fields: [tokenBlacklistBlacklistedtoken.tokenId],
		references: [tokenBlacklistOutstandingtoken.id]
	}),
}));